### ISSUE TITLE
Demos for each component

### ISSUE THREAD

**Issue by tizu69** [MCJack123/PrimeUI#1]
While the test.lua is cool n all, it's missing most of the components. I'd like to see an actual component gallery including demos on how to do different things with components, including code examples. If this is too complicated, a GitHub wiki would also work. Some of these probably aren't possible, but I feel like this would really benefit some more advanced features.

Some example ideas for a wiki:

- Editing text of a label on the fly
- Listening for `terminate` using `PrimeUI#addTask`
- Preselecting a specific selectionBox item
- Returning multiple inputs
- Enabling mouse scroll on selection boxes
- ...

**Comment by MCJack123** [comment]
1. None of the above are currently possible, and most of them will never be possible. (e.g. editing labels - you use a text box for this instead)
2. I think the test program is fairly comprehensive in showing how to use the components - maybe not having all the combinations, but that gets a bit tedious to put together. If you have more suggestions, PRs welcome.
3. I'll put up some sort of proper docs for 1.0, so people don't have to dig through the code to find it.
